# Generated by Django 5.2.1 on 2025-06-10 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='Murza Baitemir', max_length=50, verbose_name='Имя пользователя'),
            preserve_default=False,
        ),
    ]
