# Generated by Django 5.2.1 on 2025-06-10 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('Мужской', 'Мужской'), ('Женский', 'Женский')], null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='email@my.ru', max_length=254, verbose_name='E-mail'),
        ),
    ]
