# Generated by Django 5.2.1 on 2025-06-03 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_remove_carpost_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpost',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cars.currency', verbose_name='Валюта цены'),
            preserve_default=False,
        ),
    ]
