# Generated by Django 5.2.1 on 2025-06-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_carpost_deal_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dealtype',
            options={'verbose_name': 'Тип предложений', 'verbose_name_plural': 'Тип предложения'},
        ),
        migrations.AlterModelOptions(
            name='vehicletype',
            options={'verbose_name': 'Тип автомобиля', 'verbose_name_plural': 'Тип автомобилей'},
        ),
        migrations.AlterField(
            model_name='carimage',
            name='img',
            field=models.ImageField(upload_to='car/posts/'),
        ),
    ]
