# Generated by Django 5.2.1 on 2025-06-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_remove_carpost_preview_img_carimage_preview_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carimage',
            name='preview_img',
        ),
        migrations.AddField(
            model_name='carpost',
            name='preview_img',
            field=models.URLField(default='https://example.com'),
        ),
    ]
