# Generated by Django 5.2.1 on 2025-06-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_remove_carimage_preview_img_carpost_preview_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpost',
            name='description',
            field=models.TextField(default='short', verbose_name='Дополнительная информация'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carpost',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Цена'),
        ),
    ]
