# Generated by Django 5.2.1 on 2025-06-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_alter_carpost_description_alter_carpost_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpost',
            name='preview_img',
            field=models.URLField(blank=True, default='https://example.com', null=True),
        ),
    ]
