# Generated by Django 5.2.1 on 2025-06-10 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0019_alter_carpost_car_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpost',
            name='engine_volume',
            field=models.FloatField(blank=True, null=True, verbose_name='Объем двигателя (л)'),
        ),
    ]
