# Generated by Django 5.2.1 on 2025-06-10 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0020_alter_carpost_engine_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpost',
            name='unique_id',
            field=models.IntegerField(default=923849239, verbose_name='Уникальный идентификатор машины'),
            preserve_default=False,
        ),
    ]
