# Generated by Django 5.2.1 on 2025-06-10 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0021_carpost_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpost',
            name='unique_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Уникальный идентификатор машины'),
        ),
    ]
