# Generated by Django 5.2.1 on 2025-06-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='default-avatar.png', null=True, upload_to='users/avatar/'),
        ),
    ]
