# Generated by Django 5.2.1 on 2025-06-10 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.CharField(default='Кыргызстан', verbose_name='Страна проживание'),
        ),
    ]
