# Generated by Django 5.2.1 on 2025-06-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpost',
            name='currency',
            field=models.CharField(choices=[('SOM', 'Сом'), ('USD', 'Доллар')], default='Сом', verbose_name='Валюта цены'),
        ),
    ]
