# Generated by Django 5.2.1 on 2025-06-03 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_carpost_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carpost',
            name='currency',
        ),
    ]
