# Generated by Django 5.2.1 on 2025-06-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_carpost_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpost',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=12, verbose_name='Цена'),
        ),
    ]
