# Generated by Django 5.2.1 on 2025-06-05 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_carpost_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpost',
            name='deal_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.dealtype', verbose_name='Тип расчета'),
        ),
    ]
