# Generated by Django 5.2.1 on 2025-06-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_alter_dealtype_options_alter_vehicletype_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpost',
            name='preview_img',
            field=models.URLField(default='https://example.com'),
        ),
    ]
