# Generated by Django 5.2.1 on 2025-06-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_alter_carpost_preview_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpost',
            name='preview_img',
            field=models.URLField(blank=True, null=True),
        ),
    ]
