# Generated by Django 5.2.1 on 2025-06-10 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0013_alter_carpost_preview_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpost',
            name='availability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.availability', verbose_name='Наличии'),
        ),
        migrations.AlterField(
            model_name='carpost',
            name='car_brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.carmark', verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='carpost',
            name='car_generation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.cargeneration', verbose_name='Поколение'),
        ),
        migrations.AlterField(
            model_name='carpost',
            name='car_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.carmodel', verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='carpost',
            name='condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.condition', verbose_name='Техническое состояние'),
        ),
        migrations.AlterField(
            model_name='carpost',
            name='count_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.carowner', verbose_name='К-лво Владелец'),
        ),
        migrations.AlterField(
            model_name='carpost',
            name='custom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.custom', verbose_name='Расстоможен'),
        ),
        migrations.AlterField(
            model_name='carpost',
            name='fuel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.fuel', verbose_name='Тип двигателя'),
        ),
        migrations.AlterField(
            model_name='carpost',
            name='gearbox',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.gearbox', verbose_name='Коробка передач'),
        ),
        migrations.AlterField(
            model_name='carpost',
            name='steering_wheel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.steeringwheel', verbose_name='Руль'),
        ),
        migrations.AlterField(
            model_name='carpost',
            name='transmission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.transmission', verbose_name='Привод'),
        ),
    ]
