# Generated by Django 5.2.1 on 2025-06-10 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0014_alter_carpost_availability_alter_carpost_car_brand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'АВТО КАТЕГОРИЮ',
                'verbose_name_plural': 'АВТО КАТЕГОРИЯ',
            },
        ),
        migrations.AddField(
            model_name='carpost',
            name='car_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.carcategory', verbose_name='Авто категория'),
        ),
    ]
