# Generated by Django 5.2.1 on 2025-06-10 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0015_carcategory_carpost_car_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carpost',
            name='car_category',
        ),
        migrations.DeleteModel(
            name='CarCategory',
        ),
    ]
