# Generated by Django 5.2.1 on 2025-06-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0016_remove_carpost_car_category_delete_carcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpost',
            name='engine_volume',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Объем двигателя (л)'),
        ),
    ]
