# Generated by Django 5.2.1 on 2025-06-10 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0018_alter_carpost_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpost',
            name='car_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.cartype', verbose_name='Тип кузова'),
        ),
    ]
