# Generated by Django 5.2.1 on 2025-06-27 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0024_alter_carpost_year'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='carfavorite',
            unique_together=set(),
        ),
    ]
